pipeline {
    agent { node { label "maven" } }
    environment { APP_NAMESPACE = 'mfrwnc-recover' }
    parameters {
        string(name: 'DEPLOY_TAG',  description: 'Deploy to Tag')
    }
    stages {
        stage ("Test") {
            when { expression { params.DEPLOY_TAG == '' } }
            options { timeout(time: 50, unit: 'SECONDS') }
            steps {
                dir("shopping-cart-v2") {
                    sh './mvnw clean test'
                }
            }
        }
        stage ("Build Image") {
            when { expression { params.DEPLOY_TAG == '' } }
            environment { QUAY = credentials("QUAY_USER") }
            steps {
                dir("shopping-cart-v2") {
                    sh "./scripts/include-container-extensions.sh"
                    sh '''
                        ./scripts/build-and-push-image.sh \
                        -u $QUAY_USR \
                        -p $QUAY_PSW \
                        -b $BUILD_NUMBER
                    '''
                }
            }
        }
        stage ("Deploy") {
            environment { QUAY = credentials("QUAY_USER") }
            steps {
                dir ("shopping-cart-v2") {
                    script {
                        def TAG_TO_DEPLOY = "BUILD-$BUILD_NUMBER"
                        sh "echo start script: \"$TAG_TO_DEPLOY\""
                        sh "echo DEPLOY_TAG: \"$DEPLOY_TAG\""
                        if (params.DEPLOY_TAG != '' && params.DEPLOY_TAG != null) {
                            sh "echo youpi"
                            def status = sh(
                                script: "./scripts/tag-exists-in-quay.sh $QUAY_USR/do400-recover ${params.DEPLOY_TAG}",
                                returnStatus : true
                            )
                            if (status != 0) {
                                error("Tag not found in Quay")
                            }
                            sh 'echo "in IF" DEPLOYTAG="$DEPLOY_TAG" TAGTODEPLOY="$TAG_TO_DEPLOY" '
                            TAG_TO_DEPLOY = params.DEPLOY_TAG
                        }
                        sh "echo before deploy script: \"$TAG_TO_DEPLOY\""
                        sh '''
                            ./scripts/deploy-image.sh \
                            -u $QUAY_USR \
                            -n $APP_NAMESPACE \
                            -t $TAG_TO_DEPLOY
                        '''
                    }
                }
            }
        }
    }
}