pipeline {
    agent {
        node {
            label "nodejs"
        }
    }
    stages {
        stage ('Install dependencies') {
            steps {
                dir ("exchange-cli") {
                    sh "npm install"
                }
            }
        }
        stage ('Build') {
            steps {
                dir  ("exchange-cli") {
                    sh "npm run build"
                }
            }
        }
        stage ("Functionnal Tests") {
            steps {
                dir ("exchange-cli") {
                    sh "npm run test:functional"
                }
            }
        }
    }

}